"use client";

import { useState, useEffect } from "react";
import NextImage from "next/image";
import { useRouter } from "next/navigation";
import { motion, AnimatePresence } from "framer-motion";

// =============================================================================
// 2FA Settings Page
// =============================================================================

export default function TwoFASettingsPage() {
  const router = useRouter();
  const [step, setStep] = useState<"init" | "qr" | "success">("init");
  const [secret, setSecret] = useState("");
  const [otpauth, setOtpauth] = useState("");
  const [code, setCode] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState("");

  const generateSecret = async () => {
    setIsLoading(true);
    setError("");
    try {
      const response = await fetch("/api/admin/auth/2fa/setup", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${localStorage.getItem("admin-token")}`,
        },
      });
      const data = await response.json();
      if (!data.success) throw new Error(data.error);

      setSecret(data.secret);
      setOtpauth(data.otpauth);
      setStep("qr");
    } catch (err) {
      setError(
        err instanceof Error ? err.message : "Failed to generate secret",
      );
    } finally {
      setIsLoading(false);
    }
  };

  const verifyAndEnable = async () => {
    setIsLoading(true);
    setError("");
    try {
      const response = await fetch("/api/admin/auth/2fa/setup", {
        method: "PUT",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${localStorage.getItem("admin-token")}`,
        },
        body: JSON.stringify({ token: code, secret }),
      });
      const data = await response.json();
      if (!data.success) throw new Error(data.error);

      setStep("success");
    } catch (err) {
      setError(err instanceof Error ? err.message : "Verification failed");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="p-8 max-w-4xl mx-auto">
      <div className="mb-8">
        <h1 className="text-3xl font-bold text-white mb-2 font-[family-name:var(--font-mono)]">
          Security Settings
        </h1>
        <p className="text-slate-400 text-sm">
          Manage your two-factor authentication preferences.
        </p>
      </div>

      <div className="bg-[#0c0e14]/50 border border-white/10 rounded-2xl p-8 backdrop-blur-sm relative overflow-hidden">
        <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-primary/50 to-purple-500/50" />

        <div className="flex items-start gap-6">
          <div className="w-12 h-12 rounded-xl bg-primary/10 flex items-center justify-center shrink-0">
            <span className="material-symbols-outlined text-primary text-2xl">
              security
            </span>
          </div>
          <div className="flex-1">
            <h2 className="text-xl font-bold text-white mb-2">
              Two-Factor Authentication (TOTP)
            </h2>
            <p className="text-slate-400 text-sm mb-6 max-w-xl">
              Secure your account with an authenticator app like Google
              Authenticator or Authy. When enabled, you will need to provide a
              unique code generated by your app to log in.
            </p>

            <AnimatePresence mode="wait">
              {step === "init" && (
                <motion.div
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  exit={{ opacity: 0 }}
                >
                  <button
                    onClick={generateSecret}
                    disabled={isLoading}
                    className="px-6 py-3 bg-primary hover:bg-primary/90 text-white rounded-lg font-bold text-sm transition-colors flex items-center gap-2"
                  >
                    {isLoading ? "Generating..." : "Setup Authenticator App"}
                  </button>
                </motion.div>
              )}

              {step === "qr" && (
                <motion.div
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0 }}
                  className="bg-white/5 rounded-xl p-6 border border-white/10 max-w-sm"
                >
                  <div className="mb-4 bg-white p-4 rounded-lg w-fit mx-auto">
                    {/* Requires next-qrcode or similar. Fallback if not available: just use qrcode lib directly or img tag if using data url */}
                    {/* Since I don't have UseQRCode installed yet, I'll assume standard qrcode lib usage or similar is needed. 
                                    Wait, the plan said install `qrcode`. So I should use `qrcode` to generate canvas/img. 
                                    I will use a simpler approach: use `qrcode` package to generate data url in useEffect. 
                                */}
                    <QrCodeView text={otpauth} />
                  </div>

                  <p className="text-center text-xs text-slate-400 mb-4 font-mono break-all bg-black/20 p-2 rounded">
                    {secret}
                  </p>

                  <div className="space-y-4">
                    <input
                      type="text"
                      placeholder="Enter 6-digit code"
                      value={code}
                      onChange={(e) =>
                        setCode(e.target.value.replace(/\D/g, "").slice(0, 6))
                      }
                      className="w-full px-4 py-3 bg-[#1a1d25] border border-white/10 rounded-lg text-white font-mono text-center tracking-widest text-lg focus:border-primary outline-none"
                    />
                    <button
                      onClick={verifyAndEnable}
                      disabled={isLoading || code.length !== 6}
                      className="w-full py-3 bg-primary hover:bg-primary/90 text-white rounded-lg font-bold text-sm shadow-lg shadow-primary/20"
                    >
                      {isLoading ? "Verifying..." : "Verify & Enable"}
                    </button>
                  </div>
                  {error && (
                    <p className="text-red-400 text-xs text-center mt-3">
                      {error}
                    </p>
                  )}
                </motion.div>
              )}

              {step === "success" && (
                <motion.div
                  initial={{ opacity: 0, scale: 0.9 }}
                  animate={{ opacity: 1, scale: 1 }}
                  className="flex flex-col items-center py-6"
                >
                  <div className="w-16 h-16 rounded-full bg-emerald-500/20 flex items-center justify-center mb-4">
                    <span className="material-symbols-outlined text-emerald-500 text-3xl">
                      check
                    </span>
                  </div>
                  <h3 className="text-lg font-bold text-white mb-2">
                    2FA Enabled
                  </h3>
                  <p className="text-slate-400 text-sm mb-6">
                    Your account is now secured with TOTP.
                  </p>
                  <button
                    onClick={() => router.push("/admin")}
                    className="px-6 py-2 bg-white/10 hover:bg-white/20 text-white rounded-lg text-sm"
                  >
                    Go to Dashboard
                  </button>
                </motion.div>
              )}
            </AnimatePresence>
          </div>
        </div>
      </div>
    </div>
  );
}

// Helper to render QR URL
import QRCode from "qrcode";
function QrCodeView({ text }: { text: string }) {
  const [src, setSrc] = useState("");
  useEffect(() => {
    QRCode.toDataURL(text).then(setSrc);
  }, [text]);

  if (!src)
    return <div className="w-48 h-48 bg-gray-200 animate-pulse rounded" />;
  return (
    <NextImage
      src={src}
      alt="QR Code"
      width={192}
      height={192}
      className="w-48 h-48 rounded"
      unoptimized
    />
  );
}
