packages:
  - .

allowBuilds:
  "@scarf/scarf": true
  "@tree-sitter-grammars/tree-sitter-yaml": true
  argon2: true
  core-js-pure: true
  esbuild: true
  sharp: true
  tree-sitter: true
  tree-sitter-json: true
  unrs-resolver: true

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - "@scarf/scarf"
  - "@tree-sitter-grammars/tree-sitter-yaml"
  - argon2
  - core-js-pure
  - esbuild
  - tree-sitter
  - tree-sitter-json
